server:
  port: 8000
  
spring:
  datasource:
    url: jdbc:mysql://localhost:49153/db_example
    username: springuser
    password: ThePassword
  jpa:
    hibernate:
      ddl-auto: update
      
mybatis:
  type-aliases-package: com.example.module_core.model
  mapper-locations: classpath:mapper/*.xml